### ISSUE TITLE
Color tint is disabled after screen lock/logout

### ISSUE THREAD

**Issue by vt0000** [MattByName/color-tint#29]
Initial condition:
"Overlay active on start" setting is on
"Tint" toggle is on

When I logout and log back in, the "Tint" toggle is off. Same if I suspend the laptop and wake it back in case the login screen is shown. If I disable "Lock screen on suspend" in settings so I won't be prompted with a login screen, then after waking the color tint is active.

Tested on 2 different laptops running Ubuntu 24.04, both X11 and Wayland.

Either there's a bug somewhere or I'm not sure what the "Overlay active on start" setting is supposed to do. I assume  it is meant to activate the tint when the extension is started.

Otherwise a fantastic extension and the only thing working for color calibrating my laptop screen!

**Comment by MattByName** [comment]
Thanks for writing the bug report! You’re right about what the overlay active on start button is supposed to do, something has obviously broken. I’ll take a look tomorrow.Thanks again, and I’m glad you find the extension useful!MattOn 8 Aug 2024, at 12:15, vt0000 ***@***.***> wrote:﻿
Initial condition:
"Overlay active on start" setting is on
"Tint" toggle is on
When I logout and log back in, the "Tint" toggle is off. Same if I suspend the laptop and wake it back in case the login screen is shown. If I disable "Lock screen on suspend" in settings so I won't be prompted with a login screen, then after waking the color tint is active.
Tested on 2 different laptops running Ubuntu 24.04, both X11 and Wayland.
Either there's a bug somewhere or I'm not sure what the "Overlay active on start" setting is supposed to do. I assume  it is meant to activate the tint when the extension is started.
Otherwise a fantastic extension and the only thing working for color calibrating my laptop screen!

**Comment by MattByName** [comment]
I've submitted an update to the Gnome Extensions site to fix this, it should hopefully be released in a couple of days

**Comment by vt0000** [comment]
Great, it's working now! Thanks for your support!
